#name: CI with Maven and Deployment to AWS EC2 with Terraform
#
#on:
#  push:
#    branches:
#      - main
#
#env:
#  AWS_REGION: eu-west-1
#  S3_BUCKET: term-project-jars
#  TF_VERSION: 1.1.0
#  TF_WORKING_DIR: terraform
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v3
#
#      - name: Set up JDK 11
#        uses: actions/setup-java@v3
#        with:
#          java-version: '11'
#          distribution: 'temurin'
#          cache: maven
#
#      - name: Build with Maven
#        run: mvn -B package --file pom.xml
#
#      - name: Configure AWS credentials
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: ${{ env.AWS_REGION }}
#
#      - name: Set up Terraform
#        uses: hashicorp/setup-terraform@v1
#        with:
#          terraform_version: ${{ env.TF_VERSION }}
#
#      - name: Terraform Initialize
#        run: terraform init
#        working-directory: ${{ env.TF_WORKING_DIR }}
#
#      - name: Terraform Validate
#        run: terraform validate
#        working-directory: ${{ env.TF_WORKING_DIR }}
#
#      - name: Terraform Plan
#        run: terraform plan
#        working-directory: ${{ env.TF_WORKING_DIR }}
#
#      - name: Terraform Apply
#        run: terraform apply -auto-approve
#        working-directory: ${{ env.TF_WORKING_DIR }}
#
#      - name: Copy JAR to S3
#        run: |
#          aws s3 cp target/term-project-0.0.1-SNAPSHOT.jar s3://${{ env.S3_BUCKET }}/term-project-0.0.1-SNAPSHOT.jar
