name: Destroy Infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to destroy'
        required: true
        default: 'main'

env:
  AWS_REGION: eu-west-1
  TF_VERSION: 1.1.0
  TF_WORKING_DIR: terraform

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Destroy
        run: |
          terraform init -input=false -no-color -backend-config="key=${{ github.run_number }}/${{ env.environment }}/terraform.tfstate"
          terraform workspace new ${{ env.environment }}
          terraform workspace select ${{ env.environment }}
          terraform destroy -auto-approve -input=false -no-color
        working-directory: ${{ env.TF_WORKING_DIR }}
